-- CREATE  OR REPLACE TABLE audits (
--   audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   table_name       VARCHAR2(255),
--   transaction_name VARCHAR2(10),
--   by_user          VARCHAR2(30),
--   transaction_date DATE
-- );

-- CREATE OR REPLACE TRIGGER customers_audit_trg
-- AFTER UPDATE OR DELETE ON emp_copy
-- FOR EACH ROW
-- DECLARE
--   l_transaction VARCHAR2(10);
-- BEGIN
--   IF UPDATING THEN
--     l_transaction := 'UPDATE';
--   ELSIF DELETING THEN
--     l_transaction := 'DELETE';
--   END IF;

--   INSERT INTO audits (table_name, transaction_name, by_user, transaction_date)
--   VALUES ('EMP_COPY', l_transaction, USER, SYSDATE);
-- END;
-- /
-- UPDATE emp_copy SET salary = 5000 WHERE employee_id = 101;
-- DELETE FROM emp_copy WHERE employee_id = 102;
-- update emp_copy set first_name= 'aman' where employee_id=100;
-- SELECT * FROM audits ORDER BY audit_id;
-- SELECT * FROM emp_copy;



